# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.


def find_pentagonal_numbers(num):
    return [int(i*(3*i - 1)/2) for i in range(1, num)]

def find_tringular_numbers(num):
    return [int(i*(i + 1)/2) for i in range(1, num)]

def find_hexagonal_numbers(num):
    return [int(i*(2*i - 1)) for i in range(1, num)]


def main():
    threshold = 100000
    triangular_thresh = threshold * 2
    triangular_list = find_tringular_numbers(triangular_thresh)
    pent_list = find_pentagonal_numbers(threshold)
    hex_list = find_hexagonal_numbers(threshold)
    for tri_num in triangular_list[280:]:
        if tri_num in pent_list[160:] and tri_num in hex_list[140:]:
            print(tri_num)
    print('Done!')


if __name__ == '__main__':
    main()